name: A workflow for Katalon Actions
on: push
jobs:
  build:
    name: Katalon GitHub Action Sample
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Retrieve license
        run: |
          mkdir .katalon
          mkdir .katalon/license
          echo "${{ secrets.KATALON_API_KEY }}" > .katalon/license/ci.lic
      - uses: locmai/katalon-actions@master
        env:
          KATALON_ARGS: "-projectPath=\"./\" -browserType=\"Chrome\" -retry=0 -statusDelay=15 -testSuitePath=\"Test Suites/TS_RegressionTest\""