name: A workflow for Katalon Actions
on: push
jobs:
  build:
    name: Katalon GitHub Action Sample
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: locmai/katalon-actions@master
        env:
          KATALON_ARGS: -apiKey="${{ secrets.KATALON_API_KEY }}" -projectPath="./" -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"