name: A workflow for Katalon Actions
on: push
jobs:
  build:
    name: Katalon GitHub Action Sample
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: locmai/katalon-actions@master
        with:
          api-key: ${{ secrets.KATALON_API_KEY }}
          command-line: 'katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"'